development:
  OPENWEATHERMAP_API_KEY: YOUR_OPENWEATHERMAP_API_KEY_DEVELOPMENT
  WUNDERGROUND_API_KEY: YOUR_WUNDERGROUND_API_KEY_DEVELOPMENT
  ACCUWEATHER_API_KEY: YOUR_ACCUWEATHER_API_KEY_DEVELOPMENT
staging:
  OPENWEATHERMAP_API_KEY: YOUR_OPENWEATHERMAP_API_KEY_STAGING
  WUNDERGROUND_API_KEY: YOUR_WUNDERGROUND_API_KEY_STAGING
  ACCUWEATHER_API_KEY: YOUR_ACCUWEATHER_API_KEY_STAGING
production:
  OPENWEATHERMAP_API_KEY: YOUR_OPENWEATHERMAP_API_KEY_PRODUCTION
  WUNDERGROUND_API_KEY: YOUR_WUNDERGROUND_API_KEY_KEY_PRODUCTION
  ACCUWEATHER_API_KEY: YOUR_ACCUWEATHER_API_KEY_KEY_PRODUCTION

