class Config {
  static const OPENWEATHERMAP_API_KEY = "YOUR_OPENWEATHERMAP_API_KEY";
  static const WUNDERGROUND_API_KEY = "YOUR_WUNDERGROUND_API_KEY";
  static const ACCUWEATHER_API_KEY = "YOUR_ACCUWEATHER_API_KEY";
}
